name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Configure Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y automake ant autopoint cmake build-essential libtool-bin \
         patch pkg-config protobuf-compiler ragel subversion unzip git \
         flex python wget gettext

    - name: Install Android NDK
      run: |
        # 安装指定版本的NDK
        sdkmanager --install "ndk;27.3.13750724"
        

    - name: Set environment variables
      run: |
        echo "ANDROID_SDK=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        # 配置NDK路径环境变量
        echo "ANDROID_NDK=$ANDROID_SDK_ROOT/ndk/27.3.13750724" >> $GITHUB_ENV
        echo "PATH=$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools:$PATH" >> $GITHUB_ENV
        
    - name: Build VLC-Android (arm64-v8a Release)
      run: |
        chmod +x ./buildsystem/compile.sh
        ./buildsystem/compile.sh -a arm64-v8a --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: app/build/outputs/apk/release/*.apk
